
export type Investor = {
  id: number;
  name: string;
  location: string;
  sectors: string;
  stage: string;
}

export const investors: Investor[] = [
  {
    id: 1,
    name: 'Kunal Shah',
    location: 'Mumbai',
    sectors: 'Fintech, Consumer Internet, Edtech',
    stage: 'Pre-seed, Seed, Series A, Series B',
  },
  {
    id: 2,
    name: 'Anupam Mittal',
    location: 'Mumbai',
    sectors: 'Technology, Consumer Internet, SaaS',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 3,
    name: 'Sanjay Mehta',
    location: 'Mumbai',
    sectors: 'Deep Tech, Fintech, Edtech',
    stage: 'Pre-seed, Seed, Series A, Series B',
  },
  {
    id: 4,
    name: 'Rajan Anandan',
    location: 'Bangalore',
    sectors: 'SaaS, Big Data, Healthcare',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 5,
    name: 'Sachin Bansal',
    location: 'Bangalore',
    sectors: 'SaaS, AI, E-commerce',
    stage: 'Seed, Series A, Series B',
  },
  {
    id: 6,
    name: 'Binny Bansal',
    location: 'Bangalore',
    sectors: 'Consumer Internet, Fintech, Edtech',
    stage: 'Seed, Series A',
  },
  {
    id: 7,
    name: 'Vijay Shekhar Sharma',
    location: 'Delhi NCR',
    sectors: 'Fintech, Consumer Tech',
    stage: 'Series A, Series B, Series C',
  },
  {
    id: 8,
    name: 'Ratan Tata',
    location: 'Mumbai',
    sectors: 'E-commerce, Healthcare, Mobility',
    stage: 'Seed, Series A, Series B',
  },
  {
    id: 9,
    name: 'Kunal Bahl',
    location: 'Delhi NCR',
    sectors: 'Technology, Retail, Edtech',
    stage: 'Seed, Series A, Series B',
  },
  {
    id: 10,
    name: 'Rohit Bansal',
    location: 'Delhi NCR',
    sectors: 'Consumer Internet, SaaS',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 11,
    name: 'Gokul Rajaram',
    location: 'Bangalore',
    sectors: 'Technology, Fintech',
    stage: 'Series A, Series B',
  },
  {
    id: 12,
    name: 'Zishaan Hayath',
    location: 'Mumbai',
    sectors: 'Edtech, E-commerce, Mobility',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 13,
    name: 'T.V. Mohandas Pai',
    location: 'Bangalore',
    sectors: 'Technology, Women-led Startups',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 14,
    name: 'Girish Mathrubootham',
    location: 'Chennai',
    sectors: 'SaaS, Cybersecurity, Coworking',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 15,
    name: 'Sujeet Kumar',
    location: 'Bangalore',
    sectors: 'E-commerce, Fintech, Edtech',
    stage: 'Seed, Series A, Series B',
  },
  {
    id: 16,
    name: 'Gaurav Munjal',
    location: 'Bangalore',
    sectors: 'Edtech, Consumer Tech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 17,
    name: 'Ritesh Agarwal',
    location: 'Delhi NCR',
    sectors: 'Consumer Internet, Hospitality',
    stage: 'Seed, Series A, Series B',
  },
  {
    id: 18,
    name: 'Jitendra Gupta',
    location: 'Mumbai',
    sectors: 'Fintech, Consumer Internet',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 19,
    name: 'Deep Kalra',
    location: 'Delhi NCR',
    sectors: 'Travel, Edtech, Healthtech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 20,
    name: 'Rajesh Sawhney',
    location: 'Delhi NCR',
    sectors: 'Fintech, Edtech, Construction',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 21,
    name: 'Ramakant Sharma',
    location: 'Bangalore',
    sectors: 'E-commerce, SaaS',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 22,
    name: 'Amit Lakhotia',
    location: 'Delhi NCR',
    sectors: 'Fintech, Social Commerce',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 23,
    name: 'Anjali Bansal',
    location: 'Mumbai',
    sectors: 'Consumer, Fintech, Healthtech',
    stage: 'Seed, Series A, Series B',
  },
  {
    id: 24,
    name: 'Arjun Vaidya',
    location: 'Mumbai',
    sectors: 'Consumer, Wellness',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 25,
    name: 'Amrish Rau',
    location: 'Bangalore',
    sectors: 'Fintech, Payments',
    stage: 'Series A, Series B',
  },
  {
    id: 26,
    name: 'Ajeet Khurana',
    location: 'Mumbai',
    sectors: 'Travel, Media, Healthtech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 27,
    name: 'Aditya Burman',
    location: 'Delhi NCR',
    sectors: 'Health, Wellness, D2C',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 28,
    name: 'Shaival Desai',
    location: 'Ahmedabad',
    sectors: 'D2C, Foodtech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 29,
    name: 'Anand Chandrasekaran',
    location: 'Bangalore',
    sectors: 'Tech, Fintech, Consumer',
    stage: 'Pre-seed, Seed, Series A, Series B',
  },
  {
    id: 30,
    name: 'Ritesh Malik',
    location: 'Delhi NCR',
    sectors: 'Healthcare, Coworking, Travel',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 31,
    name: 'Sunil Kalra',
    location: 'Mumbai',
    sectors: 'Internet, Microfinance, Analytics',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 32,
    name: 'Sharad Sharma',
    location: 'Bangalore',
    sectors: 'Internet, SaaS',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 33,
    name: 'Dr. Ashish Gupta',
    location: 'Bangalore',
    sectors: 'Tech, Marketplace',
    stage: 'Pre-seed, Seed, Series A, Series B',
  },
  {
    id: 34,
    name: 'Ishaan Preet Singh',
    location: 'Bangalore',
    sectors: 'Consumer Internet, Deep Tech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 35,
    name: 'Sasha Mirchandani',
    location: 'Mumbai',
    sectors: 'Consumer Tech, SaaS',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 36,
    name: 'Nandini Mansinghka',
    location: 'Mumbai',
    sectors: 'Tech, Life Sciences, Marketplace',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 37,
    name: 'Vikram Chachra',
    location: 'Mumbai',
    sectors: 'Fintech, Consumer Tech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 38,
    name: 'Vaibhav Domkundwar',
    location: 'Bangalore',
    sectors: 'Deep Tech, Enterprise',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 39,
    name: 'Ajay Jain',
    location: 'Mumbai',
    sectors: 'Enterprise, Deep Tech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 40,
    name: 'Anirudh Damani',
    location: 'Mumbai',
    sectors: 'Consumer Tech, Fintech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 41,
    name: 'Sandeep Tandon',
    location: 'Mumbai',
    sectors: 'Consumer Internet, E-commerce',
    stage: 'Seed, Series A, Series B',
  },
  {
    id: 42,
    name: 'Anil Jain',
    location: 'Delhi NCR',
    sectors: 'Tech, Agritech, Fintech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 43,
    name: 'Anuj Golecha',
    location: 'Mumbai',
    sectors: 'D2C, Mobility',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 44,
    name: 'Apoorva Ranjan Sharma',
    location: 'Delhi NCR',
    sectors: 'Agritech, D2C',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 45,
    name: 'Gaurav Jain',
    location: 'Mumbai',
    sectors: 'Consumer, Fintech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 46,
    name: 'Neeraj Tyagi',
    location: 'Delhi NCR',
    sectors: 'Tech, Consumer',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 47,
    name: 'Gaurav VK Singhvi',
    location: 'Mumbai',
    sectors: 'Fintech, D2C',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 48,
    name: 'Bhawna Bhatnagar',
    location: 'Delhi NCR',
    sectors: 'Consumer Tech, Edtech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 49,
    name: 'Vikas Aggarwal',
    location: 'Delhi NCR',
    sectors: 'SaaS, Consumer',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 50,
    name: 'Saurabh Deo',
    location: 'Mumbai',
    sectors: 'Fintech, Healthtech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 51,
    name: 'Shanti Mohan',
    location: 'Bangalore',
    sectors: 'Tech, Consumer',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 52,
    name: 'Sanjay Jha',
    location: 'Bangalore',
    sectors: 'Edtech, Consumer Internet',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 53,
    name: 'Prashant Choksey',
    location: 'Mumbai',
    sectors: 'Tech, Life Sciences',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 54,
    name: 'Praveen Chakravarty',
    location: 'Mumbai',
    sectors: 'Marketplace, Mobility',
    stage: 'Seed, Series A, Series B',
  },
  {
    id: 55,
    name: 'Ramaraj R',
    location: 'Chennai',
    sectors: 'Deep Science, Fintech, D2C',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 56,
    name: 'Ashish Kacholia',
    location: 'Mumbai',
    sectors: 'Fintech, Consumer',
    stage: 'Series A, Series B',
  },
  {
    id: 57,
    name: 'Vidit Aatrey',
    location: 'Bangalore',
    sectors: 'E-commerce, Consumer Tech',
    stage: 'Seed, Series A, Series B',
  },
  {
    id: 58,
    name: 'Varun Alagh',
    location: 'Delhi NCR',
    sectors: 'D2C, Consumer',
    stage: 'Seed, Series A, Series B',
  },
  {
    id: 59,
    name: 'Sahil Barua',
    location: 'Delhi NCR',
    sectors: 'Logistics, Consumer Tech',
    stage: 'Series A, Series B',
  },
  {
    id: 60,
    name: 'Ankit Nagori',
    location: 'Bangalore',
    sectors: 'Foodtech, Consumer, Fintech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 61,
    name: 'Deepak Garg',
    location: 'Delhi NCR',
    sectors: 'Logistics, SaaS',
    stage: 'Seed, Series A, Series B',
  },
  {
    id: 62,
    name: 'Alok Mittal',
    location: 'Bangalore',
    sectors: 'Fintech, SME Lending',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 63,
    name: 'Vishal Gupta',
    location: 'Bangalore',
    sectors: 'E-commerce, Consumer Tech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 64,
    name: 'Amarpreet Singh',
    location: 'Mumbai',
    sectors: 'Consumer Internet, SaaS',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 65,
    name: 'Padmaja Ruparel',
    location: 'Delhi NCR',
    sectors: 'Tech, Consumer Services',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 66,
    name: 'Ankita Vashisht',
    location: 'Mumbai',
    sectors: 'Technology, Gender Diversity',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 67,
    name: 'Sanjay Jesrani',
    location: 'Mumbai',
    sectors: 'Consumer Internet, Fintech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 68,
    name: 'Vishal Gondal',
    location: 'Mumbai',
    sectors: 'Healthtech, Gaming',
    stage: 'Seed, Series A, Series B',
  },
  {
    id: 69,
    name: 'Pawan Munjal',
    location: 'Delhi NCR',
    sectors: 'Mobility, Consumer Tech',
    stage: 'Series A, Series B',
  },
  {
    id: 70,
    name: 'Shraddha Sharma',
    location: 'Bangalore',
    sectors: 'Media, Consumer Internet',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 71,
    name: 'Deepak Shahdadpuri',
    location: 'Mumbai',
    sectors: 'Consumer, D2C',
    stage: 'Seed, Series A, Series B',
  },
  {
    id: 72,
    name: 'Naveen Tewari',
    location: 'Bangalore',
    sectors: 'Adtech, Consumer Tech',
    stage: 'Series A, Series B',
  },
  {
    id: 73,
    name: 'Amit Gupta',
    location: 'Bangalore',
    sectors: 'Mobility, Sustainability',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 74,
    name: 'Aniruddha Malpani',
    location: 'Mumbai',
    sectors: 'Healthcare, Education',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 75,
    name: 'Saurabh Srivastava',
    location: 'Delhi NCR',
    sectors: 'Consumer Internet, SaaS',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 76,
    name: 'Ravi Machani',
    location: 'Chennai',
    sectors: 'Agritech, Deep Science',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 77,
    name: 'Vikram Gupta',
    location: 'Mumbai',
    sectors: 'Fintech, Healthtech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 78,
    name: 'Sanjay Nayar',
    location: 'Mumbai',
    sectors: 'Fintech, Consumer Tech',
    stage: 'Series A, Series B',
  },
  {
    id: 79,
    name: 'Anirudh Suri',
    location: 'Bangalore',
    sectors: 'Consumer Internet, SaaS',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 80,
    name: 'Sanjiv Bajaj',
    location: 'Pune',
    sectors: 'Fintech, D2C',
    stage: 'Series A, Series B',
  },
  {
    id: 81,
    name: 'Ravi Jaipuria',
    location: 'Delhi NCR',
    sectors: 'Foodtech, D2C',
    stage: 'Series A, Series B',
  },
  {
    id: 82,
    name: 'Kiran Mazumdar-Shaw',
    location: 'Bangalore',
    sectors: 'Biotech, Deep Tech',
    stage: 'Seed, Series A, Series B',
  },
  {
    id: 83,
    name: 'Anand Mahindra',
    location: 'Mumbai',
    sectors: 'Mobility, Consumer Tech',
    stage: 'Series A, Series B, Series C',
  },
  {
    id: 84,
    name: 'Saurabh Mukherjea',
    location: 'Mumbai',
    sectors: 'Consumer, Fintech',
    stage: 'Series A, Series B',
  },
  {
    id: 85,
    name: 'Rahul Khanna',
    location: 'Bangalore',
    sectors: 'Fintech, Enterprise Tech',
    stage: 'Series A, Series B',
  },
  {
    id: 86,
    name: 'Nikhil Kamath',
    location: 'Bangalore',
    sectors: 'Fintech, D2C',
    stage: 'Seed, Series A, Series B',
  },
  {
    id: 87,
    name: 'Nithin Kamath',
    location: 'Bangalore',
    sectors: 'Fintech, Consumer Tech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 88,
    name: 'Ankit Bhati',
    location: 'Bangalore',
    sectors: 'Mobility, Consumer Internet',
    stage: 'Series A, Series B',
  },
  {
    id: 89,
    name: 'Bhavish Aggarwal',
    location: 'Bangalore',
    sectors: 'Mobility, Deep Tech',
    stage: 'Series A, Series B, Series C',
  },
  {
    id: 90,
    name: 'Ravi Venkatesan',
    location: 'Bangalore',
    sectors: 'Social Impact, Tech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 91,
    name: 'Sanjay Swamy',
    location: 'Bangalore',
    sectors: 'Fintech, Enterprise Tech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 92,
    name: 'Vivek Khare',
    location: 'Mumbai',
    sectors: 'Consumer Internet, SaaS',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 93,
    name: 'Kris Gopalakrishnan',
    location: 'Bangalore',
    sectors: 'Deep Tech, Healthtech',
    stage: 'Seed, Series A, Series B',
  },
  {
    id: 94,
    name: 'Nandan Nilekani',
    location: 'Bangalore',
    sectors: 'Fintech, Deep Tech',
    stage: 'Series A, Series B, Series C',
  },
  {
    id: 95,
    name: 'Sridhar Vembu',
    location: 'Chennai',
    sectors: 'SaaS, Consumer Tech',
    stage: 'Seed, Series A, Series B',
  },
  {
    id: 96,
    name: 'Vijay Kedia',
    location: 'Mumbai',
    sectors: 'Consumer, Fintech',
    stage: 'Series A, Series B',
  },
  {
    id: 97,
    name: 'Sanjay Parikh',
    location: 'Mumbai',
    sectors: 'Marketplace, Consumer Tech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 98,
    name: 'Anil Srinivasan',
    location: 'Chennai',
    sectors: 'Healthtech, Edtech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 99,
    name: 'Naveen Trehan',
    location: 'Delhi NCR',
    sectors: 'Healthtech, Consumer Tech',
    stage: 'Pre-seed, Seed, Series A',
  },
  {
    id: 100,
    name: 'Radhika Aggarwal',
    location: 'Delhi NCR',
    sectors: 'E-commerce, D2C, Consumer Tech',
    stage: 'Series A, Series B',
  },
];
